# Generated by Django 3.0.7 on 2020-06-06 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20200606_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='Vacancy description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.URLField(unique=True, verbose_name='Vacancy url'),
        ),
    ]
